### ISSUE TITLE
一个编译错误

### ISSUE THREAD

**Issue by wjx0912** [sidyhe/skynet-win32#2]
1>------ 已启动生成: 项目: skynet, 配置: Debug x64 ------
1>lua-mysqlaux.c
1>c1 : fatal error C1083: 无法打开源文件: “..\..\..\skynet\lualib-src\lua-mysqlaux.c”: No such file or directory
1>已完成生成项目“skynet.vcxproj”的操作 - 失败。
========== 生成: 成功 0 个，失败 1 个，最新 14 个，跳过 0 个 ==========

**Comment by wjx0912** [comment]
源码中没有lua-mysqlaux.c，但是又参与了编译，请帮忙看看。谢啦

**Comment by sidyhe** [comment]
编的是本项目指向的skynet吗? 原生的skynet是不可以的.

**Comment by wjx0912** [comment]
是本项目的

**Comment by sidyhe** [comment]
已修复, 重新拉一下
之前更新官方的代码, 发现已无法继续兼容windows系统
所以不再更新, 回滚到最初兼容的代码 (2018.11)

**Comment by wjx0912** [comment]
@sidyhe 谢谢
